name: testnew
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.0.0
  image_picker: ^1.1.1
  firebase_storage: ^12.0.0
  firebase_database: ^11.0.0
  qr_flutter: ^4.0.0
  qr_code_scanner: ^1.0.1
  gallery_saver: ^2.0.8
  get: ^4.6.6
  flutter_barcode_scanner: ^2.0.0
  open_file: ^3.2.1
  image_gallery_saver: ^2.0.3
  screenshot: ^3.0.0
  intl: ^0.19.0
  fl_chart: ^0.68.0
  photo_view: ^0.15.0
  image: ^4.2.0
  path: ^1.9.0
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  device_info_plus: ^10.1.0
  file_picker: ^8.0.3
  url_launcher: ^6.3.0
  string_similarity: ^2.0.0
  workmanager: ^0.5.2
  pdf: ^3.10.8
  printing: ^5.12.0

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "lib/assets/lost_found_new_logo.png"
  remove_alpha_ios: true

flutter:
  assets:
    - lib/assets/default_profile_image.png
    - lib/assets/lost_found_new_logo.png
  uses-material-design: true