// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdlFFKLgW_RieqPv_9dJKKxMOzRw9kBfE',
    appId: '1:283108926250:web:0598833e2656c7074f3453',
    messagingSenderId: '283108926250',
    projectId: 'psmtest-33edc',
    authDomain: 'psmtest-33edc.firebaseapp.com',
    storageBucket: 'psmtest-33edc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5BC9S34O-ewuZ0QpBDDKxwQx12Vvgz1A',
    appId: '1:283108926250:android:9c407ea2f5afaa5b4f3453',
    messagingSenderId: '283108926250',
    projectId: 'psmtest-33edc',
    storageBucket: 'psmtest-33edc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtgMjQlmlkMlTg1736mKQiJxVvbDHYrHU',
    appId: '1:283108926250:ios:d0cca343ee52d8304f3453',
    messagingSenderId: '283108926250',
    projectId: 'psmtest-33edc',
    storageBucket: 'psmtest-33edc.appspot.com',
    iosBundleId: 'com.example.testnew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtgMjQlmlkMlTg1736mKQiJxVvbDHYrHU',
    appId: '1:283108926250:ios:491db188c89f76304f3453',
    messagingSenderId: '283108926250',
    projectId: 'psmtest-33edc',
    storageBucket: 'psmtest-33edc.appspot.com',
    iosBundleId: 'com.example.testnew.RunnerTests',
  );
}
